version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jinmin-sam-app-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-98sn3nulb2p"
s3_prefix = "jinmin-sam-app-2"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"
parameter_overrides = "StackName=\"jinmin-sam-app-2\" Stage=\"dev\" S3Bucket=\"jinmin-sam-app-2\""
profile = "default"
